name: to_do_list
description: TODO лист.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  sqflite: ^2.2.8+4
  get_it: ^7.6.0
  dio: ^5.2.1+1
  device_info_plus: ^9.0.2
  uuid: ^3.0.7
  flutter_riverpod: ^2.3.6
  freezed_annotation: ^2.2.0
  envied: ^0.3.0+3
  equatable: ^2.0.5
  path_provider: ^2.0.15
  sqflite_common_ffi: ^2.2.5
  universal_internet_checker: ^0.1.2
  url_strategy: ^0.2.0
  firebase_core: ^2.14.0
  sqflite_common_ffi_web: ^0.3.6

provider:
  intl: ^0.18.0

dependency_overrides:
  # path_provider_android: 2.0.11 

dev_dependencies:
  flutter_test:
    sdk: flutter

  freeze: ^1.0.0
  flutter_lints: ^2.0.1
  build_runner: ^2.4.5
  json_serializable: ^6.5.4
  envied_generator: ^0.3.0+3

flutter:

  uses-material-design: true
  
  assets:
    - l10n/

  fonts:
      - family: AppIcons
        fonts:
          - asset: assets/fonts/AppIcons.ttf
      - family: Roboto
        fonts:
          - asset: assets/fonts/Roboto-Regular.ttf
          - asset: assets/fonts/Roboto-Medium.ttf

