name: to_do_list
description: TODO лист.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  get_it: ^7.6.0
  # Sqflite
  sqflite: ^2.2.8+4
  sqflite_common_ffi: ^2.2.5
  # Riverpod
  flutter_riverpod: ^2.3.6
  riverpod_messages: ^1.0.2
  # Secure token
  envied: ^0.3.0+3
  
  # Firebase
  firebase_core: ^2.14.0
  firebase_crashlytics: ^3.3.3
  firebase_analytics: ^10.4.3
  firebase_auth: ^4.6.3
  firebase_ui_auth: ^1.5.0
  cloud_firestore: ^4.8.2
  firebase_remote_config: ^4.2.3
  
  # Internet
  internet_connection_checker: ^1.0.0+1
  url_strategy: ^0.2.0
  http: ^1.1.0
  dio: ^5.2.1+1
  # Flavor
  flutter_flavorizr: ^2.2.1
  # Freezed
  freezed: ^2.3.5
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  # Other
  device_info_plus: ^9.0.2
  uuid: ^3.0.7
  equatable: ^2.0.5
  path_provider: ^2.0.15

provider:
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  freeze: ^1.0.0
  flutter_lints: ^2.0.1
  build_runner: ^2.4.5
  json_serializable: ^6.5.4
  envied_generator: ^0.3.0+3

flutter:

  uses-material-design: true
  
  assets:
    - l10n/

  fonts:
      - family: AppIcons
        fonts:
          - asset: assets/fonts/AppIcons.ttf
      - family: Roboto
        fonts:
          - asset: assets/fonts/Roboto-Regular.ttf
          - asset: assets/fonts/Roboto-Medium.ttf

flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"

  flavors:
    dev:
      app:
        name: "To Do List"

      android:
        applicationId: "online.mytodo.dev"
      ios:
        bundleId: "online.mytodo.dev"

    prod:
      app:
        name: "To Do List"

      android:
        applicationId: "online.mytodo.prod"
      ios:
        bundleId: "online.mytodo.prod"