name: to_do_list
description: TODO лист.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  sqflite: ^2.2.8+4
  path_provider: ^2.0.15
  dartz: ^0.10.1
  get_it: ^7.6.0
  flutter_bloc: ^8.1.3
  intl: ^0.18.0
  provider: ^6.0.5
  flutter_localizations:
    sdk: flutter
  http: ^1.0.0
  shared_preferences: ^2.1.2
  internet_connection_checker: ^1.0.0+1
  dio: ^5.2.1+1
  device_info_plus: ^9.0.2
  uuid: ^3.0.7
  logging: ^1.2.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.5

flutter:

  uses-material-design: true

  fonts:
      - family: AppIcons
        fonts:
          - asset: assets/fonts/AppIcons.ttf
      - family: Roboto
        fonts:
          - asset: assets/fonts/Roboto-Regular.ttf
          - asset: assets/fonts/Roboto-Medium.ttf

